from nltk.stem import WordNetLemmatizer


vagueness_words = [
    'about',
    'abundant',
    'accelerated',
    'acceptable',
    'accessible',
    'accommodating',
    'accomplished',
    'achievable',
    'adapted',
    'adept',
    'adequate',
    'adjacent',
    'admirable',
    'adroit',
    'advantageous',
    'adventitious',
    'advisable',
    'agile',
    'agreeable',
    'alike',
    'almost',
    'alright',
    'amenable',
    'ample',
    'analogous',
    'any',
    'apace',
    'apparent',
    'applicable',
    'applied',
    'apposite',
    'apprehensible',
    'appropriate',
    'approximate',
    'appurtenant',
    'apropos',
    'apt',
    'associable',
    'assumable',
    'available',
    'average',
    'await',
    'aweful',
    'bad',
    'basic',
    'becoming',
    'befitting',
    'believable',
    'belonging',
    'benefic',
    'beneficial',
    'benign',
    'benignant',
    'biddable',
    'big',
    'binding',
    'blameless',
    'blur',
    'bordering',
    'bottom-line',
    'brisk',
    'bummer',
    'can',
    'capable',
    'cardinal',
    'carefree',
    'careless',
    'charitable',
    'cheap',
    'cheesy',
    'chief',
    'classy',
    'clear',
    'clear-cut',
    'clever',
    'cogent',
    'coherent',
    'comfortable',
    'comfy',
    'commendable',
    'commending',
    'commensurate',
    'commit',
    'commodious',
    'common',
    'commonplace',
    'comparable',
    'comparative',
    'compelling',
    'competent',
    'compliant',
    'composed',
    'comprehensible',
    'compulsory',
    'conceivable',
    'conditional',
    'conducive',
    'conformable',
    'congent',
    'congign',
    'congruous',
    'conscientious',
    'considerable',
    'considerate',
    'conspicuous',
    'constant',
    'contempo',
    'contemporary',
    'contended',
    'contingent',
    'convenient',
    'conventional',
    'convincing',
    'copacetic',
    'copious',
    'correct',
    'correspondingly',
    'could',
    'countless',
    'crappy',
    'credible',
    'creeping',
    'crummy',
    'customary',
    'dawdling',
    'deceivable',
    'decent',
    'decisive',
    'defective',
    'deficient',
    'definite',
    'delaying',
    'deliberarte',
    'deluxe',
    'denoting',
    'dependable',
    'dependent',
    'depending',
    'desirable',
    'desired',
    'dexterous',
    'dilatory',
    'direct',
    'discretionary',
    'disinclinced',
    'dissatisfactory',
    'dormant',
    'downer',
    'dreadful',
    'due',
    'durable',
    'easy',
    'economical',
    'effective',
    'effectual',
    'efficacious',
    'efficient',
    'effortless',
    'elective',
    'elementary',
    'eloquent',
    'emphatic',
    'employable',
    'endless',
    'enduring',
    'energetic',
    'enough',
    'equal',
    'equivalently',
    'erroneous',
    'essential',
    'estimable',
    'estimated',
    'eventually',
    'everywhere',
    'evident',
    'excellent',
    'exceptional',
    'exemplary',
    'exigent',
    'exiguous',
    'expect',
    'expected',
    'expedite',
    'expeditiously',
    'expendient',
    'expendiently',
    'experienced',
    'expert',
    'explicit',
    'exploitable',
    'expressing',
    'expressive',
    'extensive',
    'extravagant',
    'extremely',
    'facile',
    'facund',
    'fair',
    'fallacious',
    'familiar',
    'far',
    'fast',
    'faulty',
    'favorable',
    'favoring',
    'favourable',
    'favouring',
    'feasible',
    'felicitous',
    'finally',
    'firm',
    'first-class',
    'fit',
    'fitted',
    'fitting',
    'fixed',
    'flawless',
    'flexible',
    'forceful',
    'forcible',
    'fortuitous',
    'fresh',
    'fruitful',
    'functional',
    'fundamental',
    'furthermore',
    'galore',
    'garbage',
    'general',
    'generous',
    'genuine',
    'germane',
    'gettable',
    'gifted',
    'gnarly',
    'godawful',
    'good',
    'gradual',
    'gradually',
    'graspable',
    'gratifying',
    'great',
    'grody',
    'gross',
    'grungy',
    'guessed',
    'guiltless',
    'gullible',
    'habitual',
    'hale',
    'halfway',
    'handy',
    'hardy',
    'healthy',
    'heaps',
    'hearty',
    'heavy',
    'helpful',
    'hereafter',
    'honorable',
    'honourable',
    'hope',
    'hypothetical',
    'icky',
    'ideal',
    'ill',
    'imaginable',
    'immeasurable',
    'imminent',
    'impending',
    'imperative',
    'imperceptible',
    'imperfect',
    'important',
    'imprecise',
    'inactive',
    'inadequate',
    'include',
    'incomparably',
    'incomplete',
    'inconsequential',
    'inconsiderable',
    'incontrovertible',
    'incorrect',
    'incorrupt',
    'inculpable',
    'indeterminate',
    'indicative',
    'indispensable',
    'indolent',
    'inert',
    'inferior',
    'infrequent',
    'insufficient',
    'intelligent',
    'intelligible',
    'interest',
    'ipressive',
    'irreprehensible',
    'irreproachable',
    'jam-packed',
    'junky',
    'justified',
    'knowable',
    'knowing',
    'kosher',
    'lackadaisical',
    'laggard',
    'lagging',
    'large',
    'lasting',
    'late',
    'late',
    'latent',
    'latter',
    'lavish',
    'leaden',
    'lean',
    'legible',
    'legit',
    'leisurely',
    'less',
    'lethargic',
    'liberal',
    'licensed',
    'light',
    'likely',
    'listless',
    'literal',
    'little',
    'littlest',
    'loads',
    'loitering',
    'long',
    'look',
    'looming',
    'loose',
    'lot',
    'lotsa',
    'lousy',
    'loyal',
    'lucent',
    'lucid',
    'lucrative',
    'manage',
    'manageable',
    'mandatory',
    'manifest',
    'manifestable',
    'many',
    'marvelous',
    'massiely',
    'masterly',
    'matching',
    'maximum',
    'may',
    'maybe',
    'meager',
    'meaning',
    'measurable',
    'measured',
    'median',
    'meet',
    'mega',
    'merciful',
    'mere',
    'merest',
    'meritious',
    'methodical',
    'middling',
    'might',
    'mighty',
    'mild',
    'minimal',
    'minimum',
    'minor',
    'minority',
    'minute',
    'moderate',
    'modern',
    'modernistic',
    'momentous',
    'much',
    'mucho',
    'musculer',
    'must-have',
    'naive',
    'natural',
    'near',
    'nearby',
    'neat',
    'necessary',
    'needed',
    'needful',
    'negligent',
    'negligible',
    'neighbouring',
    'neoteric',
    'new',
    'newborn',
    'newfanglend',
    'nice',
    'nimble',
    'normal',
    'notably',
    'noticeably',
    'novel',
    'obedient',
    'objectionable',
    'obligatory',
    'obtainable',
    'obvious',
    'occasional',
    'off',
    'okay',
    'opportune',
    'orderly',
    'ordinary',
    'organized',
    'orthodox',
    'painless',
    'palpable',
    'paramount',
    'particularly',
    'passable',
    'passive',
    'peaceful',
    'peachy',
    'perceptible',
    'perchance',
    'perfect',
    'perhaps',
    'permanent',
    'perspicuous',
    'persuasive',
    'pertinent',
    'petty',
    'phelegmatic',
    'piddling',
    'piecemeal',
    'plain',
    'plausibly',
    'pleasent',
    'pleasing',
    'plenteous',
    'plentiful',
    'plodding',
    'politic',
    'poor',
    'popular',
    'positive',
    'possible',
    'possibly',
    'potent',
    'potential',
    'powerful',
    'powerhouse',
    'practicable',
    'practicably',
    'practical',
    'pragmatic',
    'praiseworthy',
    'precious',
    'precise',
    'preferable',
    'preganant',
    'prerequisite',
    'prerogative',
    'presentable',
    'pressing',
    'presumably',
    'presumptively',
    'prevalent',
    'prime',
    'principal',
    'privileged',
    'probable',
    'probably',
    'procrastinating',
    'productive',
    'proficient',
    'profitable',
    'profuse',
    'promising',
    'promptly',
    'pronounced',
    'proper',
    'propitious',
    'prosperous',
    'proximately',
    'pure',
    'purposive',
    'qualified',
    'quality',
    'quick',
    'quiet',
    'quintessential',
    'quit',
    'quite',
    'rapid',
    'rare',
    'raunchy',
    'realizable',
    'reasonable',
    'reasonably',
    'recent',
    'recognizable',
    'rectitude',
    'regular',
    'reinforced',
    'relative',
    'relatively',
    'relevant',
    'reliable',
    'reluctant',
    'remiss',
    'remperate',
    'representative',
    'reputable',
    'required',
    'requisite',
    'resembling',
    'resonable',
    'respectable',
    'rich',
    'right',
    'right-minded',
    'righteous',
    'righteousness',
    'rightful',
    'robust',
    'rough',
    'roughly',
    'routine',
    'royal',
    'rugged',
    'sad',
    'safe',
    'salubrious',
    'salutary',
    'sane',
    'satisfactory',
    'satisfying',
    'scads',
    'scant',
    'scanty',
    'scarce',
    'scattered',
    'scattering',
    'sctive',
    'secure',
    'seemingly',
    'seemly',
    'seldom',
    'semioccasional',
    'sententious',
    'serious',
    'serviceable',
    'several',
    'sharp',
    'short',
    'should',
    'significant',
    'similar',
    'similarly',
    'simple',
    'sinewy',
    'sizable',
    'skillful',
    'skimpy',
    'slack',
    'sleepy',
    'slender',
    'slight',
    'slightest',
    'slightly',
    'slim',
    'slipshod',
    'slothful',
    'slow',
    'sluggish',
    'smallest',
    'smooth',
    'snaillike',
    'soft',
    'solid',
    'some',
    'sometimes',
    'somewhat',
    'soon',
    'sound',
    'sparse',
    'specific',
    'splendid',
    'sporadic',
    'stable',
    'stagnant',
    'stalewart',
    'standard',
    'stark',
    'staunch',
    'steady',
    'stingy',
    'stinking',
    'stout',
    'straggling',
    'straightforward',
    'strapping',
    'strict',
    'striking',
    'strong',
    'stupendous',
    'sturdy',
    'submissive',
    'substandard',
    'substantial',
    'successful',
    'sufficient',
    'sufficing',
    'suggestive',
    'suitable',
    'suited',
    'super',
    'superb',
    'superior',
    'supine',
    'supposing',
    'surmised',
    'susceptible',
    'sustain',
    'swell',
    'swift',
    'symbolic',
    'talented',
    'tardy',
    'tenacious',
    'thereafter',
    'thin',
    'thinkable',
    'thorough',
    'thus',
    'tiniest',
    'today',
    'tolerable',
    'too',
    'torpid',
    'tortoiselike',
    'tough',
    'toward',
    'tractable',
    'traditional',
    'trained',
    'transparent',
    'transpicuous',
    'treasure',
    'trenchant',
    'trifling',
    'trustworthy',
    'typic',
    'typical',
    'ultimately',
    'unacceptable',
    'unambiguous',
    'unavoidable',
    'unblemished',
    'unblur',
    'unblurred',
    'unburdensome',
    'uncertain',
    'uncommon',
    'uncomplicated',
    'uncontaminated',
    'uncorrupted',
    'undamaged',
    'undemanding',
    'unequivocal',
    'unexceptional',
    'unfrequent',
    'unimpaired',
    'uninvolved',
    'unmistakable',
    'unobjectionable',
    'unoppressive',
    'unprecise',
    'unquestionable',
    'unsatisfactory',
    'unspoiled',
    'unsuspicious',
    'untroublesome',
    'unyielding',
    'urgent',
    'usable',
    'useful',
    'utile',
    'valid',
    'valuable',
    'velocious',
    'very',
    'viable',
    'vigorous',
    'virtue',
    'virtuous',
    'vital',
    'voluminous',
    'wanted',
    'weighty',
    'well',
    'well-suited',
    'well-timed',
    'whatever',
    'wholesime',
    'wholesome',
    'wieldy',
    'will',
    'wonderful',
    'workable',
    'worse',
    'worth',
    'worthwhile',
    'yielding'
]

vagueness_phrases = [
    'a bit',
    'a few',
    'a little',
    'able bodied',
    'all other',
    'all the other',
    'all important',
    'allow for',
    'as applicable',
    'as appropriate',
    'as far as possible',
    'as little as possible',
    'as much as possible',
    'as necessary',
    'as possible',
    'as required',
    'at best',
    'at last',
    'at least',
    'at most',
    'at worst',
    'based on',
    'be able to',
    'be capable of',
    'bear in mind',
    'best possible',
    'bit by bit',
    'capability of',
    'capability to',
    'capable of',
    'certain degree',
    'certain extent',
    'certain level',
    'certain point',
    'child\'s play',
    'close to',
    'cut out for',
    'de rigueur',
    'equal to',
    'few and far between',
    'hard as nails',
    'heavy duty',
    'hot off the fire',
    'hot off the press',
    'if in case',
    'in addition',
    'in character',
    'in file feather',
    'in general',
    'in keeping',
    'in line for',
    'in the running',
    'invumbent on',
    'just out',
    'latter day',
    'least possible',
    'lots of',
    'loud enough',
    'no end',
    'not entirely',
    'not fully',
    'not good',
    'not limited to',
    'not many',
    'not so good',
    'not strictly',
    'not too many',
    'not wholly',
    'number among',
    'of assistance',
    'of service',
    'of use',
    'part of',
    'piece of cake',
    'prsent day',
    'scarcely any',
    'should have',
    'slow moving',
    'sooner or later',
    'subject to',
    'take care',
    'take into account',
    'take into consideration',
    'taken care of',
    'takes care',
    'the latest',
    'then as well',
    'think about',
    'to the point',
    'up to',
    'up to date',
    'up to snuff',
    'user friendly',
    'verging on',
    'well built',
    'well founded',
    'well made',
    'widely spaced',
    'within control',
    'within limits',
    'within reach',
]

subjectivity_words = [
    'agnate',
    'aim',
    'akin',
    'alike',
    'allied',
    'analogous',
    'await',
    'bad',
    'better',
    'bigger',
    'choice',
    'coincident',
    'coinciding',
    'companion',
    'comparable',
    'congruous',
    'consider',
    'consonant',
    'contemplate',
    'correlative',
    'corresponding',
    'design',
    'equivalently',
    'exceeding',
    'exceptional',
    'expect',
    'finer',
    'fitter',
    'furthermore',
    'greater',
    'homogeneous',
    'hope',
    'identical',
    'ill',
    'imply',
    'improved',
    'include',
    'indicate',
    'intend',
    'intimate',
    'kin',
    'kindred',
    'larger',
    'like',
    'look',
    'matching',
    'parallel',
    'poor',
    'prederred',
    'preferable',
    'prominent',
    'propose',
    'reciprocal',
    'related',
    'resembling',
    'same',
    'sharpened',
    'signify',
    'similar',
    'similarly',
    'sophisticated',
    'superior',
    'surpassing',
    'thus',
    'too',
    'twin',
    'uniform',
    'worse',
    'worthier'
]

subjectivity_phrases = [
    'allow for',
    'allude to',
    'as possible',
    'bear in mind',
    'get at',
    'having in mind',
    'higher quality',
    'hint at',
    'in addition',
    'in agreement',
    'more appropriate',
    'more desirable',
    'more fitting',
    'more select',
    'more suitable',
    'more useful',
    'more valuble',
    'much the same',
    'not so good',
    'number among',
    'refer to',
    'souped up',
    'take into account',
    'take into consideration',
    'then as well',
    'think about'
]

optionality_words = [
    'avoidably',
    'can',
    'conceivably',
    'eventually',
    'finally',
    'hereafter',
    'likely',
    'may',
    'maybe',
    'optionally',
    'peradventure',
    'perchnace',
    'perhaps',
    'possibly',
    'probably',
    'someday',
    'sometime',
    'ulimately',
    'unessentially',
    'uselessly'
]

optionality_phrases = [
    'after all',
    'at all',
    'at last',
    'at the end of the day',
    'be allowed',
    'be authorized',
    'be permitted',
    'by any chance',
    'by any means',
    'can do',
    'could be',
    'god willing',
    'if appropriate',
    'if in case',
    'if needed',
    'if possible',
    'in any way',
    'in future',
    'in the course of time',
    'in the end',
    'in the long run',
    'not impossibly',
    'one day',
    'sooner or later',
    'when all is said and done',
    'within the realm of possibility'
]

implicitness_words = [
    'above',
    'abutting',
    'adherents',
    'adjacent',
    'adjoining',
    'aforementioned',
    'after',
    'aloft',
    'alongside',
    'antecedent',
    'anterior',
    'atop',
    'attached',
    'audience',
    'below',
    'beneath',
    'beside',
    'beyond',
    'circle',
    'clientage',
    'clientele',
    'close',
    'coming',
    'completion',
    'conclusion',
    'consequent',
    'conterminous',
    'cortege',
    'coterie',
    'dependents',
    'earlier',
    'ending',
    'ensuring',
    'entourage',
    'erstwhile',
    'ex',
    'fans',
    'finale',
    'finis',
    'finish',
    'following',
    'foregoing',
    'group',
    'groupies',
    'here',
    'high',
    'it',
    'last',
    'later',
    'meeting',
    'nearest',
    'neighboring',
    'next',
    'omega',
    'over',
    'overhead',
    'past',
    'patronage',
    'patrons',
    'precedent',
    'preceding',
    'previous',
    'proximate',
    'public',
    'raised',
    'retinue',
    'rout',
    'sometime',
    'succeeding',
    'such',
    'suite',
    'superior',
    'support',
    'supporters',
    'termination',
    'that',
    'these',
    'they',
    'this',
    'those',
    'touching',
    'under',
    'underneath',
    'upon'
]

implicitness_phrases = [
    'a certain',
    'a particluar',
    'already stated',
    'back to back',
    'down from',
    'hangers on',
    'hard by',
    'on high',
    'on the side',
    'on top of',
    'one time',
    'side by side',
    'the above mentioned',
    'the indicated',
    'the particular',
    'the present',
]

# imperatives = ['shall', 'must', 'is required to', 'are applicable', 'are to', 'responsible for', 'will', 'should', 'could', 'would']
# conjunctions = ['and', 'after', 'although', 'as long as', 'before', 'but', 'else', 'if', 'in order', 'in case', 'nor', 'or', 'otherwise', 'once', 'since', 'then', 'though', 'till', 'unless', 'until', 'when', 'whenever', 'where', 'whereas', 'wherever', 'while', 'yet']




lemmatizer = WordNetLemmatizer()

def is_vague(words, lemmatized_words, sentence):
    res = [False, []]
    for i in range(len(words)):
        if words[i] in vagueness_words or lemmatized_words[i] in vagueness_words:
            res[1].append(words[i])
    for phrase in vagueness_phrases:
        if phrase in sentence:
            res[1].append(phrase)
    if len(res[1])>0:
        res[0] = True
    return res

def is_subjective(words, lemmatized_words, sentence):
    res = [False, []]
    for i in range(len(words)):
        if words[i] in subjectivity_words or lemmatized_words[i] in subjectivity_words:
            res[1].append(words[i])
    for phrase in subjectivity_phrases:
        if phrase in sentence:
            res[1].append(phrase)
    if len(res[1])>0:
        res[0] = True
    return res

def is_optional(words, lemmatized_words, sentence):
    res = [False, []]
    for i in range(len(words)):
        if words[i] in optionality_words or lemmatized_words[i] in optionality_words:
            res[1].append(words[i])
    for phrase in optionality_phrases:
        if phrase in sentence:
            res[1].append(phrase)
    if len(res[1])>0:
        res[0] = True
    return res

def is_implicit(words, lemmatized_words, sentence):
    res = [False, []]
    for i in range(len(words)):
        if words[i] in implicitness_words or lemmatized_words[i] in implicitness_words:
            res[1].append(words[i])
    for phrase in implicitness_phrases:
        if phrase in sentence:
            res[1].append(phrase)
    if len(res[1])>0:
        res[0] = True
    return res




def check_ambiguity(sentence):
    words = sentence.split(' ')
    lemmatized_words = []
    for word in words:
        lemmatized_words.append(lemmatizer.lemmatize(word))
    vsoi = [[], [], [], []]
    vsoi[0] = is_vague(words, lemmatized_words, sentence)
    vsoi[1] = is_subjective(words, lemmatized_words, sentence)
    vsoi[2] = is_optional(words, lemmatized_words, sentence)
    vsoi[3] = is_implicit(words, lemmatized_words, sentence)
    if vsoi[0]==[False, []] and vsoi[1]==[False, []] and vsoi[2]==[False, []] and vsoi[3]==[False, []]:
        return [False, vsoi]
    return [True, vsoi]

# ress = check_ambiguity("The software can be heavy or light.")
# print(ress)












