import re

vagueness = [
    'a bit',
    'a few',
    'a little',
    'able bodied',
    'about',
    'abundant',
    'accelerated',
    'acceptable',
    'accessible',
    'accommodating',
    'accomplished',
    'achievable',
    'adapted',
    'adept',
    'adequate',
    'adjacent',
    'admirable',
    'adroit',
    'advantageous',
    'adventitious',
    'advisable',
    'agile',
    'agreeable',
    'alike',
    'all other',
    'all the other',
    'all-important',
    'allow for',
    'almost',
    'alright',
    'amenable',
    'ample',
    'analogous',
    'any',
    'apace',
    'apparent',
    'applicable',
    'applied',
    'apposite',
    'apprehensible',
    'appropriate',
    'approximate',
    'appurtenant',
    'apropos',
    'apt',
    'as applicable',
    'as appropriate',
    'as far as possible',
    'as little as possible',
    'as much as possible',
    'as necessary',
    'as possible',
    'as required',
    'associable',
    'assumable',
    'at best',
    'at last',
    'at least',
    'at most',
    'at worst',
    'available',
    'average',
    'await',
    'aweful',
    'bad',
    'based on',
    'basic',
    'be able to',
    'be capable of',
    'bear in mind',
    'becoming',
    'befitting',
    'believable',
    'belonging',
    'benefic',
    'beneficial',
    'benign',
    'benignant',
    'best possible',
    'biddable',
    'big',
    'binding',
    'bit by bit',
    'blameless',
    'blur',
    'bordering',
    'bottom-line',
    'brisk',
    'bummer',
    'can',
    'capability of',
    'capability to',
    'capable',
    'capable of',
    'cardinal',
    'carefree',
    'careless',
    'certain degre',
    'certain extent',
    'certain level',
    'certain point',
    'charitable',
    'cheap',
    'cheesy',
    'chief',
    'child\'s play',
    'classy',
    'clear',
    'clear-cut',
    'clever',
    'close to',
    'close to',
    'cogent',
    'coherent',
    'comfortable',
    'comfy',
    'commendable',
    'commending',
    'commensurate',
    'commit',
    'commodious',
    'common',
    'commonplace',
    'comparable',
    'comparative',
    'compelling',
    'competent',
    'compliant',
    'composed',
    'comprehensible',
    'compulsory',
    'conceivable',
    'conditional',
    'conducive',
    'conformable',
    'congent',
    'congign',
    'congruous',
    'conscientious',
    'considerable',
    'considerate',
    'conspicuous',
    'constant',
    'contempo',
    'contemporary',
    'contended',
    'contingent',
    'convenient',
    'conventional',
    'convincing',
    'copacetic',
    'copious',
    'correct',
    'correspondingly',
    'could',
    'countless',
    'crappy',
    'credible',
    'creeping',
    'crummy',
    'customary',
    'cut out for',
    'dawdling',
    'de rigueur',
    'deceivable',
    'decent',
    'decisive',
    'defective',
    'deficient',
    'definite',
    'delaying',
    'deliberarte',
    'deluxe',
    'denoting',
    'dependable',
    'dependent',
    'depending',
    'desirable',
    'desired',
    'dexterous',
    'dilatory',
    'direct',
    'discretionary',
    'disinclinced',
    'dissatisfactory',
    'dormant',
    'downer',
    'dreadful',
    'due',
    'durable',
    'easy',
    'economical',
    'effective',
    'effectual',
    'efficacious',
    'efficient',
    'effortless',
    'elective',
    'elementary',
    'eloquent',
    'emphatic',
    'employable',
    'endless',
    'enduring',
    'energetic',
    'enough',
    'equal',
    'equal to',
    'equivalently',
    'erroneous',
    'essential',
    'estimable',
    'estimated',
    'eventually',
    'everywhere',
    'evident',
    'excellent',
    'exceptional',
    'exemplary',
    'exigent',
    'exiguous',
    'expect',
    'expected',
    'expedite',
    'expeditiously',
    'expendient',
    'expendiently',
    'experienced',
    'expert',
    'explicit',
    'exploitable',
    'expressing',
    'expressive',
    'extensive',
    'extravagant',
    'extremely',
    'facile',
    'facund',
    'fair',
    'fallacious',
    'familiar',
    'far',
    'fast',
    'faulty',
    'favorable',
    'favoring',
    'favourable',
    'favouring',
    'feasible',
    'felicitous',
    'few and far between',
    'finally',
    'firm',
    'first-class',
    'fit',
    'fitted',
    'fitting',
    'fixed',
    'flawless',
    'flexible',
    'forceful',
    'forcible',
    'fortuitous',
    'fresh',
    'fruitful',
    'functional',
    'fundamental',
    'furthermore',
    'galore',
    'garbage',
    'general',
    'generous',
    'genuine',
    'germane',
    'gettable',
    'gifted',
    'gnarly',
    'godawful',
    'good',
    'gradual',
    'gradually',
    'graspable',
    'gratifying',
    'great',
    'grody',
    'gross',
    'grungy',
    'guessed',
    'guiltless',
    'gullible',
    'habitual',
    'hale',
    'halfway',
    'handy',
    'hard as nails',
    'hardy',
    'healthy',
    'heaps',
    'hearty',
    'heavy',
    'heavy duty',
    'helpful',
    'helpful',
    'hereafter',
    'honorable',
    'honourable',
    'hope',
    'hot off the fire',
    'hot off the press',
    'hypothetical',
    'icky',
    'ideal',
    'if in case',
    'ill',
    'imaginable',
    'immeasurable',
    'imminent',
    'impending',
    'imperative',
    'imperceptible',
    'imperfect',
    'important',
    'imprecise',
    'in addition',
    'in character',
    'in file feather',
    'in general',
    'in keeping',
    'in line for',
    'in the running',
    'inactive',
    'inadequate',
    'include',
    'incomparably',
    'incomplete',
    'inconsequential',
    'inconsiderable',
    'incontrovertible',
    'incorrect',
    'incorrupt',
    'inculpable',
    'indeterminate',
    'indicative',
    'indispensable',
    'indolent',
    'inert',
    'inferior',
    'infrequent',
    'insufficient',
    'intelligent',
    'intelligible',
    'interest',
    'invumbent on',
    'ipressive',
    'irreprehensible',
    'irreproachable',
    'jam-packed',
    'junky',
    'just out',
    'justified',
    'knowable',
    'knowing',
    'kosher',
    'lackadaisical',
    'laggard',
    'lagging',
    'large',
    'lasting',
    'late',
    'late',
    'latent',
    'latter',
    'latter day',
    'lavish',
    'leaden',
    'lean',
    'least possible',
    'legible',
    'legit',
    'leisurely',
    'less',
    'lethargic',
    'liberal',
    'licensed',
    'light',
    'likely',
    'listless',
    'literal',
    'little',
    'littlest',
    'loads',
    'loitering',
    'long',
    'look',
    'looming',
    'loose',
    'lot',
    'lotsa',
    'loud enough',
    'lousy',
    'loyal',
    'lucent',
    'lucid',
    'lucrative',
    'manage',
    'manageable',
    'mandatory',
    'manifest',
    'manifestable',
    'many',
    'marvelous',
    'massiely',
    'masterly',
    'matching',
    'maximum',
    'may',
    'maybe',
    'meager',
    'meaning',
    'measurable',
    'measured',
    'median',
    'meet',
    'mega',
    'merciful',
    'mere',
    'merest',
    'meritious',
    'methodical',
    'middling',
    'might',
    'mighty',
    'mild',
    'minimal',
    'minimum',
    'minor',
    'minority',
    'minute',
    'moderate',
    'modern',
    'modernistic',
    'momentous',
    'much',
    'mucho',
    'musculer',
    'must-have',
    'naive',
    'natural',
    'near',
    'nearby',
    'neat',
    'necessary',
    'needed',
    'needful',
    'negligent',
    'negligible',
    'neighbouring',
    'neoteric',
    'new',
    'newborn',
    'newfanglend',
    'nice',
    'nimble',
    'no end',
    'normal',
    'not entirely',
    'not fully',
    'not good',
    'not limited to',
    'not many',
    'not so good',
    'not strictly',
    'not too many',
    'not wholly',
    'notably',
    'noticeably',
    'novel',
    'number among',
    'obedient',
    'objectionable',
    'obligatory',
    'obtainable',
    'obvious',
    'occasional',
    'of assistance',
    'of service',
    'of use',
    'off',
    'okay',
    'opportune',
    'orderly',
    'ordinary',
    'organized',
    'orthodox',
    'painless',
    'palpable',
    'paramount',
    'part of',
    'particularly',
    'passable',
    'passive',
    'peaceful',
    'peachy',
    'perceptible',
    'perchance',
    'perfect',
    'perhaps',
    'permanent',
    'perspicuous',
    'persuasive',
    'pertinent',
    'petty',
    'phelegmatic',
    'piddling',
    'piece of cake',
    'piecemeal',
    'plain',
    'plausibly',
    'pleasent',
    'pleasing',
    'plenteous',
    'plentiful',
    'plodding',
    'politic',
    'poor',
    'popular',
    'positive',
    'possible',
    'possibly',
    'potent',
    'potential',
    'powerful',
    'powerhouse',
    'practicable',
    'practicably',
    'practical',
    'pragmatic',
    'praiseworthy',
    'precious',
    'precise',
    'preferable',
    'preganant',
    'prerequisite',
    'prerogative',
    'presentable',
    'pressing',
    'presumably',
    'presumptively',
    'prevalent',
    'prime',
    'principal',
    'privileged',
    'probable',
    'probably',
    'procrastinating',
    'productive',
    'proficient',
    'profitable',
    'profuse',
    'promising',
    'promptly',
    'pronounced',
    'proper',
    'propitious',
    'prosperous',
    'proximately',
    'prsent day',
    'pure',
    'purposive',
    'qualified',
    'quality',
    'quick',
    'quiet',
    'quintessential',
    'quit',
    'quite',
    'rapid',
    'rare',
    'raunchy',
    'realizable',
    'reasonable',
    'reasonably',
    'recent',
    'recognizable',
    'rectitude',
    'regular',
    'reinforced',
    'relative',
    'relatively',
    'relevant',
    'reliable',
    'reluctant',
    'remiss',
    'remperate',
    'representative',
    'reputable',
    'required',
    'requisite',
    'resembling',
    'resonable',
    'respectable',
    'rich',
    'right',
    'right-minded',
    'righteous',
    'righteousness',
    'rightful',
    'robust',
    'rough',
    'roughly',
    'routine',
    'royal',
    'rugged',
    'sad',
    'safe',
    'salubrious',
    'salutary',
    'sane',
    'satisfactory',
    'satisfying',
    'scads',
    'scant',
    'scanty',
    'scarce',
    'scarcely any',
    'scattered',
    'scattering',
    'sctive',
    'secure',
    'seemingly',
    'seemly',
    'seldom',
    'semioccasional',
    'sententious',
    'serious',
    'serviceable',
    'several',
    'sharp',
    'short',
    'should',
    'should have',
    'significant',
    'similar',
    'similarly',
    'simple',
    'sinewy',
    'sizable',
    'skillful',
    'skimpy',
    'slack',
    'sleepy',
    'slender',
    'slight',
    'slightest',
    'slightly',
    'slim',
    'slipshod',
    'slothful',
    'slow',
    'slow moving',
    'sluggish',
    'smallest',
    'smooth',
    'snaillike',
    'soft',
    'solid',
    'some',
    'sometimes',
    'somewhat',
    'soon',
    'sooner or later',
    'sound',
    'sparse',
    'specific',
    'splendid',
    'sporadic',
    'stable',
    'stagnant',
    'stalewart',
    'standard',
    'stark',
    'staunch',
    'steady',
    'stingy',
    'stinking',
    'stout',
    'straggling',
    'straightforward',
    'strapping',
    'strict',
    'striking',
    'strong',
    'stupendous',
    'sturdy',
    'subject to',
    'submissive',
    'substandard',
    'substantial',
    'successful',
    'sufficient',
    'sufficing',
    'suggestive',
    'suitable',
    'suited',
    'super',
    'superb',
    'superior',
    'supine',
    'supposing',
    'surmised',
    'susceptible',
    'sustain',
    'swell',
    'swift',
    'symbolic',
    'take care',
    'take into account',
    'take into consideration',
    'taken care of',
    'takes care',
    'talented',
    'tardy',
    'tenacious',
    'the latest',
    'then as well',
    'thereafter',
    'thin',
    'think about',
    'thinkable',
    'thorough',
    'thus',
    'tiniest',
    'to the point',
    'today',
    'tolerable',
    'too',
    'torpid',
    'tortoiselike',
    'tough',
    'toward',
    'tractable',
    'traditional',
    'trained',
    'transparent',
    'transpicuous',
    'treasure',
    'trenchant',
    'trifling',
    'trustworthy',
    'typic',
    'typical',
    'ultimately',
    'unacceptable',
    'unambiguous',
    'unavoidable',
    'unblemished',
    'unblur',
    'unblurred',
    'unburdensome',
    'uncertain',
    'uncommon',
    'uncomplicated',
    'uncontaminated',
    'uncorrupted',
    'undamaged',
    'undemanding',
    'unequivocal',
    'unexceptional',
    'unfrequent',
    'unimpaired',
    'uninvolved',
    'unmistakable',
    'unobjectionable',
    'unoppressive',
    'unprecise',
    'unquestionable',
    'unsatisfactory',
    'unspoiled',
    'unsuspicious',
    'untroublesome',
    'unyielding',
    'up to',
    'up to date',
    'up to snuff',
    'up tp',
    'urgent',
    'usable',
    'useful',
    'user friendly',
    'utile',
    'valid',
    'valuable',
    'velocious',
    'verging on',
    'very',
    'viable',
    'vigorous',
    'virtue',
    'virtuous',
    'vital',
    'voluminous',
    'wanted',
    'weighty',
    'well',
    'well built',
    'well founded',
    'well made',
    'well-suited',
    'well-timed',
    'whatever',
    'wholesime',
    'wholesome',
    'widely spaced',
    'wieldy',
    'will',
    'within control',
    'within limits',
    'within reach',
    'wonderful',
    'workable',
    'worse',
    'worth',
    'worthwhile',
    'yielding'
]

subjectivity = [
    'agnate',
    'aim',
    'akin',
    'alike',
    'allied',
    'allow for',
    'allude to',
    'analogous',
    'as possible',
    'await',
    'bad',
    'bear in mind',
    'better',
    'bigger',
    'choice',
    'coincident',
    'coinciding',
    'companion',
    'comparable',
    'congruous',
    'consider',
    'consonant',
    'contemplate',
    'correlative',
    'corresponding',
    'design',
    'equivalently',
    'exceeding',
    'exceptional',
    'expect',
    'finer',
    'fitter',
    'furthermore',
    'get at',
    'greater',
    'having in mind',
    'higher quality',
    'hint at',
    'homogeneous',
    'hope',
    'identical',
    'ill',
    'imply',
    'improved',
    'in addition',
    'in agreement',
    'include',
    'indicate',
    'intend',
    'intimate',
    'kin',
    'kindred',
    'larger',
    'like',
    'look',
    'matching',
    'more appropriate',
    'more desirable',
    'more fitting',
    'more select',
    'more suitable',
    'more useful',
    'more valuble',
    'much the same',
    'not so good',
    'number among',
    'parallel',
    'poor',
    'prederred',
    'preferable',
    'prominent',
    'propose',
    'reciprocal',
    'refer to',
    'related',
    'resembling',
    'same',
    'sharpened',
    'signify',
    'similar',
    'similarly',
    'sophisticated',
    'souped up',
    'superior',
    'surpassing',
    'take into account',
    'take into consideration',
    'then as well',
    'think about',
    'thus',
    'too',
    'twin',
    'uniform',
    'worse',
    'worthier'
]

optionality = [
    'after all',
    'at all',
    'at last',
    'at the end of the day',
    'avoidably',
    'be allowed',
    'be authorized',
    'be permitted',
    'by any chance',
    'by any means',
    'can',
    'can do',
    'could be',
    'conceivably',
    'eventually',
    'finally',
    'god willing',
    'hereafter',
    'if appropriate',
    'if in case',
    'if needed',
    'if possible',
    'in any way',
    'in future',
    'in the course of time',
    'in the end',
    'in the long run',
    'likely',
    'may',
    'maybe',
    'not impossibly',
    'one day',
    'optionally',
    'peradventure',
    'perchnace',
    'perhaps',
    'possibly',
    'probably',
    'someday',
    'sometime',
    'sooner or later',
    'ulimately',
    'unessentially',
    'uselessly',
    'when all is said and done',
    'within the realm of possibility'
]

implicitness = [
    'a certain',
    'a particluar',
    'above',
    'abutting',
    'adherents',
    'adjacent',
    'adjoining ',
    'aforementioned',
    'after',
    'aloft',
    'alongside',
    'already stated',
    'antecedent',
    'anterior',
    'atop',
    'attached',
    'audience',
    'back to back',
    'below',
    'beneath',
    'beside',
    'beyond',
    'circle',
    'clientage',
    'clientele',
    'close',
    'coming',
    'completion',
    'conclusion',
    'consequent',
    'conterminous',
    'cortege',
    'coterie',
    'dependents',
    'down from',
    'earlier',
    'ending',
    'ensuring',
    'entourage',
    'erstwhile',
    'ex',
    'fans',
    'finale',
    'finis',
    'finish',
    'following',
    'foregoing',
    'group',
    'groupies',
    'hangers on',
    'hard by',
    'here',
    'high',
    'it',
    'last',
    'later ',
    'meeting',
    'nearest',
    'neighboring',
    'next',
    'omega',
    'on high',
    'on the side',
    'on top of',
    'one',
    'one time',
    'over',
    'overhead',
    'past',
    'patronage',
    'patrons',
    'precedent',
    'preceding',
    'previous',
    'proximate',
    'public',
    'raised',
    'retinue',
    'rout',
    'side by side',
    'sometime',
    'succeeding ',
    'such',
    'suite',
    'superior',
    'support',
    'supporters',
    'termination',
    'that',
    'the above mentioned',
    'the indicated',
    'the particular',
    'the present',
    'these',
    'they',
    'this',
    'those',
    'touching',
    'under',
    'underneath',
    'upon'
]

# imperatives = ['shall', 'must', 'is required to', 'are applicable', 'are to', 'responsible for', 'will', 'should', 'could', 'would']
# conjunctions : ['and', 'after', 'although', 'as long as', 'before', 'but', 'else', 'if', 'in order', 'in case', 'nor', 'or', 'otherwise', 'once', 'since', 'then', 'though', 'till', 'unless', 'until', 'when', 'whenever', 'where', 'whereas', 'wherever', 'while', 'yet']




def is_vague(words):
    res = [False, []]
    for word in words:
        if word in vagueness:
            res[1].append(word)
    if len(res[1])>0:
        res[0] = True
    return res

def is_subjective(words):
    res = [False, []]
    for word in words:
        if word in subjectivity:
            res[1].append(word)
    if len(res[1])>0:
        res[0] = True
    return res

def is_optional(words):
    res = [False, []]
    for word in words:
        if word in optionality:
            res[1].append(word)
    if len(res[1])>0:
        res[0] = True
    return res

def is_implicit(words):
    res = [False, []]
    for word in words:
        if word in implicitness:
            res[1].append(word)
    if len(res[1])>0:
        res[0] = True
    return res


def check_ambiguity(sentence):
    words = sentence.split(' ')
    vsoi = [[], [], [], []]
    vsoi[0] = is_vague(words)
    vsoi[1] = is_subjective(words)
    vsoi[2] = is_optional(words)
    vsoi[3] = is_implicit(words)
    if vsoi[0]==[False, []] and vsoi[1]==[False, []] and vsoi[2]==[False, []] and vsoi[3]==[False, []]:
        return [False, vsoi]
    return [True, vsoi]

# ress = check_ambiguity("The software can be heavy or light.")
# print(ress)