# Generated by Django 4.0.4 on 2022-12-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file',
            field=models.FileField(upload_to='srs.pdf'),
        ),
    ]
