# Generated by Django 4.0.4 on 2022-12-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_file_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
